// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"github.com/pochemuto/homealone-go/alice"
	"github.com/pochemuto/homealone-go/homealone"
)

// Injectors from wire.go:

func initializeApp() (Application, error) {
	bot := homealone.NewBot()
	aliceAlice := alice.NewAlice()
	application := NewApplication(bot, aliceAlice)
	return application, nil
}

// wire.go:

type Application struct {
	Bot   homealone.Bot
	Alice alice.Alice
}

func NewApplication(
	bot homealone.Bot, alice2 alice.Alice,

) Application {
	return Application{
		Bot:   bot,
		Alice: alice2,
	}
}

func InitializeApplication() (Application, error) {
	app, err := initializeApp()
	if err != nil {
		return Application{}, fmt.Errorf("app initialization error: %w", err)
	}

	return app, nil
}
